site_name: Apunts UD02 — Introducció a Java (DAM)
site_description: Apunts de la UD02 per a Programació 1r DAM
docs_dir: 'md/ud02'
site_dir: 'docs'
theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
  palette:
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
    - search
    - glightbox
    - pdf-export:
        combined: true
        enabled_if_env: ENABLE_PDF_EXPORT
    - print-site
    - page-to-pdf        
    
  

extra_css:
 - style.css



nav:
  - "Inici": "index.md"
  - "UD02":
    - "UD02 – Introducció a Java (DAM)": "ud02/01-introduccio-a-java.md"
    - "1. Introducció": "ud02/03-introduccio.md"
    - "2 Agenda": "ud02/02-agenda.md"
    - "3 Introducció a Java": "ud02/03-introduccio.md"
    - "4. Instal·lació del JDK": "ud02/04-installacio-del-jdk.md"
    - "5. Instal·lació de Visual Studio Code": "ud02/05-installacio-de-visual-studio-code.md"
    - "6 El primer programa: “Hola Món”": "ud02/06-el-primer-programa-hola-mon.md"
    - "7. Variables i tipus": "ud02/07-variables-i-tipus.md"
    - "8. Comprovació de condicions": "ud02/08-comprovacio-de-condicions.md"
    - "9. Bucles": "ud02/09-bucles.md"
    - "10.Tipus de bucles en Java": "ud02/10-tipus-de-bucles-en-java.md"
    - "11.Control del flux dins dels bucles": "ud02/11-control-del-flux-dins-dels-bucles.md"
    - "12. Arrays i cadenes": "ud02/12-arrays-i-cadenes.md"
    - "13. Dades introduïdes per l’usuari": "ud02/13-dadesUsuari.md"
    - "14. Parse (conversió String → número)": "ud02/14-parse-conversio-string-número.md"


